Repository flojoy-ai/nodes, pull requests merged in 2023-05, with the labels that each got.

#17 Format all nodes
  AI_ML/OBJECT_DETECTION/OBJECT_DETECTION.py
  GENERATORS/SIMULATIONS/CONSTANT/CONSTANT.py
  GENERATORS/SIMULATIONS/FEEDBACK/FEEDBACK.py
  GENERATORS/SIMULATIONS/LINSPACE/LINSPACE.py
  GENERATORS/SIMULATIONS/RAND/RAND.py
  GENERATORS/SIMULATIONS/SECOND_ORDER_SYSTEM/SECOND_ORDER_SYSTEM.py
  GENERATORS/SIMULATIONS/SINE/SINE.py
  INSTRUMENTS/Keithley/Keithley2400/KEITHLEY2400.py
  INSTRUMENTS/Labjack/LabjackU3/LABJACKU3.py
  INSTRUMENTS/Phidget/Phidget22/PHIDGET22.py
  INSTRUMENTS/WEB_CAM/CAMERA/CAMERA.py
  LOADERS/CLOUD_DATABASE/LOADER/LOADER.py
  LOADERS/LOCAL_FILE_SYSTEM/LOCAL_FILE.py
  LOGIC_GATES/CONDITIONALS/CONDITIONAL.py
  LOGIC_GATES/LOOPS/GOTO.py
  LOGIC_GATES/LOOPS/LOOP.py
  LOGIC_GATES/LOOPS/__init__.py
  LOGIC_GATES/TERMINATORS/END.py
  LOGIC_GATES/TIMERS/TIMER.py
  LOGIC_GATES/TIMERS/__init__.py
  TRANSFORMERS/ARITHMETIC/ABS/ABS.py
  TRANSFORMERS/ARITHMETIC/ADD/ADD.py
  TRANSFORMERS/ARITHMETIC/MULTIPLY/MULTIPLY.py
  TRANSFORMERS/ARITHMETIC/SUBTRACT/SUBTRACT.py
  TRANSFORMERS/MATRIX_MANIPULATION/INVERT/INVERT.py
  TRANSFORMERS/MATRIX_MANIPULATION/MATMUL/MATMUL.py
  TRANSFORMERS/SIGNAL_PROCESSING/BUTTER/BUTTER.py
  TRANSFORMERS/SIGNAL_PROCESSING/FIR/FIR.py
  TRANSFORMERS/SIGNAL_PROCESSING/PID/PID.py
  TRANSFORMERS/SIGNAL_PROCESSING/SAVGOL/SAVGOL.py
  VISUALIZERS/PLOTLY/BAR/BAR.py
  VISUALIZERS/PLOTLY/HISTOGRAM/HISTOGRAM.py
  VISUALIZERS/PLOTLY/IMAGE/IMAGE.py
  VISUALIZERS/PLOTLY/LINE/LINE.py
  VISUALIZERS/PLOTLY/SCATTER/SCATTER.py
  VISUALIZERS/PLOTLY/SCATTER3D/SCATTER3D.py
  VISUALIZERS/PLOTLY/SURFACE3D/SURFACE3D.py
  VISUALIZERS/template.py
Labels: enhancement

#24 remove extra argument of 'modes' from plotly scatter function for BAR…
  VISUALIZERS/PLOTLY/BAR/BAR.py
Labels: bug-fixed

#25 Added new node SK Learn Image
  GENERATORS/SAMPLE_IMAGES/SKLEARN_IMAGE/SKLEARNIMAGE.py
  MANIFEST/sklearnimage.manifest.yaml
Labels: enhancement

#31 new node: R Dataset, Table
  GENERATORS/SAMPLE_DATASETS/R_DATASET/R_DATASET.py
  GENERATORS/SAMPLE_IMAGES/SKLEARN_IMAGE/SKLEARNIMAGE.py
  MANIFEST/r_dataset.manifest.yaml
  MANIFEST/table_plotly.manifest.yaml
  VISUALIZERS/PLOTLY/TABLE/TABLE.py
Labels: enhancement

#21 Declare specific pip dependencies in node manifest file
  MANIFEST/keithley2400.manifest.yaml
  MANIFEST/labjacku3.manifest.yaml
  MANIFEST/linspace.manifest.yaml
  MANIFEST/object_detection.manifest.yaml
  MANIFEST/phidget22.manifest.yaml
Labels: enhancement

#32 format all manifest yaml file to match yaml standard
  LOADERS/LOCAL_FILE_SYSTEM/LOCAL_FILE.py
  LOADERS/LOCAL_FILE_SYSTEM/assets/astronaut.png
  MANIFEST/3d_scatter.manifest.yaml
  MANIFEST/3d_surface.manifest.yaml
  MANIFEST/abs.manifest.yaml
  MANIFEST/add.manifest.yaml
  MANIFEST/bar_chart.manifest.yaml
  MANIFEST/butter.manifest.yaml
  MANIFEST/camera.manifest.yaml
  MANIFEST/conditional.manifest.yaml
  MANIFEST/constant.manifest.yaml
  MANIFEST/end.manifest.yaml
  MANIFEST/feedback.manifest.yaml
  MANIFEST/fir.manifest.yaml
  MANIFEST/goto.manifest.yaml
  MANIFEST/histogram.manifest.yaml
  MANIFEST/image.manifest.yaml
  MANIFEST/invert.manifest.yaml
  MANIFEST/keithley2400.manifest.yaml
  MANIFEST/labjacku3.manifest.yaml
  MANIFEST/line.manifest.yaml
  MANIFEST/linspace.manifest.yaml
  MANIFEST/loader.manifest.yaml
  MANIFEST/local_file_loader.manifest.yaml
  MANIFEST/loop.manifest.yaml
  MANIFEST/matmul.manifest.yaml
  MANIFEST/multiply.manifest.yaml
  MANIFEST/object_detection.manifest.yaml
  MANIFEST/phidget22.manifest.yaml
  MANIFEST/pid.manifest.yaml
  MANIFEST/rand.manifest.yaml
  MANIFEST/savgol.manifest.yaml
  MANIFEST/scatter.manifest.yaml
  MANIFEST/second_order_system.manifest.yaml
  MANIFEST/select_array.manifest.yaml
  MANIFEST/serial.manifest.yaml
  MANIFEST/sine.manifest.yaml
  MANIFEST/subtract.manifest.yaml
  MANIFEST/timer.manifest.yaml
  MANIFEST/timeseries.manifest.yaml
Labels: enhancement

#34 update plotly viz nodes to accept dataframe
  VISUALIZERS/PLOTLY/BAR/BAR.py
  VISUALIZERS/PLOTLY/HISTOGRAM/HISTOGRAM.py
  VISUALIZERS/PLOTLY/LINE/LINE.py
  VISUALIZERS/PLOTLY/SCATTER/SCATTER.py
  VISUALIZERS/PLOTLY/TABLE/TABLE.py
Labels: enhancement

#33 new node: Plotly Dataset
  GENERATORS/SAMPLE_DATASETS/PLOTLY_DATASET/PLOTLY_DATASET.py
  MANIFEST/plotly_dataset.manifest.yaml
Labels: enhancement

#41 Camera node
  AI_ML/OBJECT_DETECTION/OBJECT_DETECTION.py
  INSTRUMENTS/WEB_CAM/CAMERA/CAMERA.py
  INSTRUMENTS/WEB_CAM/CAMERA/assets/astronaut.png
  INSTRUMENTS/__init__.py
  LOADERS/LOCAL_FILE_SYSTEM/LOCAL_FILE.py
  MANIFEST/camera.manifest.yaml
  MANIFEST/image_smoothing.manifest.yaml
  TRANSFORMERS/IMAGE_PROCESSING/IMAGE_SMOOTHING/IMAGE_SMOOTHING.py
Labels: enhancement

#44 change param type to select for sample datasets and sample images
  MANIFEST/r_dataset.manifest.yaml
  MANIFEST/sklearnimage.manifest.yaml
Labels: enhancement

#40 proper types specified for nodes
  AI_ML/OBJECT_DETECTION/OBJECT_DETECTION.py
  GENERATORS/SAMPLE_IMAGES/SKLEARN_IMAGE/SKLEARNIMAGE.py
  GENERATORS/SIMULATIONS/CONSTANT/CONSTANT.py
  GENERATORS/SIMULATIONS/FEEDBACK/FEEDBACK.py
  GENERATORS/SIMULATIONS/LINSPACE/LINSPACE.py
  GENERATORS/SIMULATIONS/RAND/RAND.py
  GENERATORS/SIMULATIONS/SECOND_ORDER_SYSTEM/SECOND_ORDER_SYSTEM.py
  GENERATORS/SIMULATIONS/SINE/SINE.py
  GENERATORS/SIMULATIONS/TIMESERIES/TIMESERIES.py
  INSTRUMENTS/Keithley/Keithley2400/KEITHLEY2400.py
  INSTRUMENTS/Labjack/LabjackU3/LABJACKU3.py
  INSTRUMENTS/Phidget/Phidget22/PHIDGET22.py
  INSTRUMENTS/Stepper_Motor/STEPPER_DRIVER_TIC.py
  INSTRUMENTS/Stepper_Motor/STEPPER_DRIVER_TIC_KNOB.py
  INSTRUMENTS/WEB_CAM/CAMERA/CAMERA.py
  LOADERS/CLOUD_DATABASE/LOADER/LOADER.py
  LOADERS/LOCAL_FILE_SYSTEM/LOCAL_FILE.py
  LOGIC_GATES/CONDITIONALS/CONDITIONAL.py
  LOGIC_GATES/LOOPS/GOTO.py
  LOGIC_GATES/LOOPS/LOOP.py
  LOGIC_GATES/TERMINATORS/END.py
  LOGIC_GATES/TIMERS/TIMER.py
  TRANSFORMERS/ARITHMETIC/ABS/ABS.py
  TRANSFORMERS/ARITHMETIC/ADD/ADD.py
  TRANSFORMERS/ARITHMETIC/MULTIPLY/MULTIPLY.py
  TRANSFORMERS/ARITHMETIC/SUBTRACT/SUBTRACT.py
  TRANSFORMERS/MATRIX_MANIPULATION/INVERT/INVERT.py
  TRANSFORMERS/MATRIX_MANIPULATION/MATMUL/MATMUL.py
  TRANSFORMERS/SELECT_ARRAY/SELECT_ARRAY/SELECT_ARRAY.py
  TRANSFORMERS/SIGNAL_PROCESSING/BUTTER/BUTTER.py
  TRANSFORMERS/SIGNAL_PROCESSING/FIR/FIR.py
  TRANSFORMERS/SIGNAL_PROCESSING/PID/PID.py
  TRANSFORMERS/SIGNAL_PROCESSING/SAVGOL/SAVGOL.py
  VISUALIZERS/PLOTLY/BAR/BAR.py
  VISUALIZERS/PLOTLY/HISTOGRAM/HISTOGRAM.py
  VISUALIZERS/PLOTLY/IMAGE/IMAGE.py
  VISUALIZERS/PLOTLY/LINE/LINE.py
  VISUALIZERS/PLOTLY/SCATTER/SCATTER.py
  VISUALIZERS/PLOTLY/SCATTER3D/SCATTER3D.py
  VISUALIZERS/PLOTLY/SURFACE3D/SURFACE3D.py
  VISUALIZERS/PLOTLY/TABLE/TABLE.py
Labels: good first issue

#45 new viz node: BIG_NUMBER
  LOGIC_GATES/LOOPS/LOOP.py
  MANIFEST/big_number.manifest.yml
  VISUALIZERS/PLOTLY/BIG NUMBER/BIG_NUMBER.py
Labels: enhancement

#60 fix table node set plotly figure correctly
  VISUALIZERS/PLOTLY/TABLE/TABLE.py
Labels: bug-fixed
